### ISSUE TITLE
Custom Helper methods

### ISSUE THREAD

**Issue by eyaleizenberg** [emilioforrer/haml_coffee_assets#131]
Hi,
I would like to create various helper methods for using Rails + Backbone + HAML coffee.

In Handlebars I have a general application_helper.js.coffee file which looks something like this:
do (Handlebars, Routes) ->
  Handlebars.registerHelper 'something', (a, b)->
     "#{a} #{b}"

Is there something similar in haml coffee?

Thanks a lot!

**Comment by whatcould** [comment]
See #25
