### ISSUE TITLE
multiline operator throws block level too deep error

### ISSUE THREAD

**Issue by raorao** [emilioforrer/haml_coffee_assets#134]
It seems that an element using the multiline operator causes an error to be thrown when it is preceded by an element nested at the appropriate depth. for instance:

```haml
/ throws error
%div
  %span
    %span
%span{ |
    "foo" => "bar", |
    "baz" => 'quz' }
 
/ does not throw error
%div
  %span
    %span
%span{ |
      "foo" => "bar", |
      "baz" => 'quz' }

**Comment by TheKidCoder** [comment]
Closing this as it should be opened @ https://github.com/netzpirat/haml-coffee
