### ISSUE TITLE
Rails 4.2.*

### ISSUE THREAD

**Issue by niels-s** [emilioforrer/haml_coffee_assets#139]
Hey guys,

I have a Rails 4.2.* project which comes with sprockets version 3.* at the moment.
The gemspec for the project indicates it's depending on sprockets 2.*
I'm wondering if it's only a mater of upgrading the gemspec to support the newer sprockets version, if that's the case I would create a Pull Request.

But since I'm not familiar with the project I was hoping some one with some more experience could give some advice.

**Comment by hbarudin** [comment]
Bump to this; I'm trying to use this with a Rails 4.2 project and getting the error message `couldn't find file 'hamlcoffee' with type 'application/javascript'` when I try to `require hamlcoffee`. I will look in the project, but like @niels-s , I am not super familiar with the project, so I'm not sure what generates/places/locations the necessary JS files.

**Comment by aprescott** [comment]
I'm also encountering an issue with the dependency on `~> 2.0`. There are problems with `foo` vs `foo/index.js` for assets, related to https://github.com/rails/sprockets-rails/pull/241 and https://github.com/rails/sprockets/pull/36. I'm trying to update to the latest Sprockets 3.x to try and resolve it, but I can't because of this gem.

**Comment by ccverak** [comment]
I'm stuck with sprocket 2.x dependency too, is there any plan to support sprockets 3.x?

**Comment by aprescott** [comment]
@ccverak I believe this project is still missing a maintainer. #130.

**Comment by bolek** [comment]
@aprescott I believe this might have been fixed with the new sprockets-rails release https://github.com/rails/sprockets-rails/issues/257
