### ISSUE TITLE
Configuration is not working

### ISSUE THREAD

**Issue by USvER** [emilioforrer/haml_coffee_assets#142]
Try to change some defaults and it seems that configuration is not working.

Added this in **application.rb**:

      config.hamlcoffee.namespace = 'window.TEMPLATE'

Inspecting the config object i can see that it has a proper values, but generated templates still uses 'window.JST' namespace.

I have used 'rake assets:clean' and restarted rails numerous times. Also i have tried to configure using initializer with "HamlCoffeeAssets.config do |config|" with no luck.

Any ideas why configuration is not working?

**Comment by TheKidCoder** [comment]
Can you open a rails console and post your `RailsApp::Application.config.hamlcoffee` ?

**Comment by USvER** [comment]
Sorry, don't have access to that project anymore.

**Comment by TheKidCoder** [comment]
No problem, figured this was a dead issues. Closing.
