### ISSUE TITLE
Don't see a maintenance near 2 years

### ISSUE THREAD

**Issue by willingchangthernguyen** [emilioforrer/haml_coffee_assets#145]
Hi Author 

The project is paused ?
I don't see you update to sprocket 3 
Thanks
Wil

**Comment by pironim** [comment]
@willingchangthernguyen gem does not have maintainer at the moment.  Check this thread https://github.com/netzpirat/haml_coffee_assets/issues/128

**Comment by jasonfb** [comment]
@willingchangthernguyen --- We think he passed away in April 2014

**Comment by iRonin** [comment]
Which fork was proposed?

**Comment by jasonfb** [comment]
Gihub informed me they do not have EOL procedures in place for a situation like this, so this repo should be considered abandoned.

**Comment by pironim** [comment]
I think somebody can create another gem with name like `hamlc_assets` :(

**Comment by jasonfb** [comment]
>>I think somebody can create another gem with name like hamlc_assets :(
  :+1:

**Comment by pironim** [comment]
it has a MIT license and it totally legal as far as I know.

**Comment by thedeeno** [comment]
I followed up with the rubygems team - we'll see if they get back to me. Another gem might be the faster solution. I don't use this project anymore so I'm happy to endorse another maintainer/fork.

**Comment by thedeeno** [comment]
I can update the readme to reflect the new location

**Comment by pironim** [comment]
@thedeeno 
maybe readme can be updated with text like 
Gem looking for a new home or maintainer.. (like [Guard README](https://github.com/guard/guard))
big header at the top can speed up this process

**Comment by jasonfb** [comment]
@thedeeno -- if you have access to this repository please shut it down and let's plan on migrating the gem to another place.
