### ISSUE TITLE
WARNING: Author has died; repository not maintained

### ISSUE THREAD

**Issue by jasonfb** [emilioforrer/haml_coffee_assets#148]
When asked about a transfer-of-root procedures, Github has informed me

>>We aren't able to do this without explicit permission from owners of both the root repository and the fork.

Since it is unknown at this time if Mr. Kressler's next-of-kin has access to his email address(es) and/or any interest in transferring root of this repo, this repository should be considered unmaintained. 

RIP @netzpirat

**Comment by TheKidCoder** [comment]
The Github & Rubygems accounts have been transferred to @emilioforrer. Closing.
