### ISSUE TITLE
fix for sprockets ~> 3.5

### ISSUE THREAD

**Issue by modosc** [emilioforrer/haml_coffee_assets#149]
i know this is not maintained anymore, just filing this as a fyi for anyone else running into the same issue:

https://github.com/vouch/haml_coffee_assets/commit/02d5643e40d84bad82a3b6ce536c9f6415581d9a

**Comment by JIucToyxuu** [comment]
Maybe be interesting - already exists  https://github.com/drivy/haml_coffee_assets. This repo add sprockets 3.x sometime ago.
