### ISSUE TITLE
Asking to precompile jquery.self.js 

### ISSUE THREAD

**Issue by gotchahn** [emilioforrer/haml_coffee_assets#155]
Hi, I am testing the new branch `release/v2.0.0` but the `Jasmine` tests I have for JavaScript stuffs are now failing with:

```
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( jquery.self.js )` to `config/initializers/assets.rb` and restart your server
```

what could be the reason?

**Comment by TheKidCoder** [comment]
Can you give more information about your environment and show what you currently have in your precompile array?

**Comment by gotchahn** [comment]
Env:
```
rails 4.2.6
ruby 2.2.4
sprockets-rails (3.1.1)
haml_coffee_assets (2.0.0)
teaspoon-jasmine (2.3.4)
` ``
And my precompile just have my additional manifests and some individual js files. All of this was just fine before installing the new `release/2.0.0` branch.

**Comment by mathieujobin** [comment]
this does not appear to be a bug with the gem, but I assume all assets must be precompiled for use with jasmine.

closing
