### ISSUE TITLE
Syntax errors doesn't highlight the template line

### ISSUE THREAD

**Issue by theoo** [emilioforrer/haml_coffee_assets#156]
I'm upgrading from version 1.1.0 (and I upgraded many other gems because I'm migrating from rails 4.1 to Rails 5), and if there is a syntax error in a template the corresponding line is not found in the trace.

This is pretty simple to reproduce, just add an indent where it's not supposed to be and reload.
The following error will be raised "Block level too deep in line 409", but the line number is not correct and the source points to line 47 of the ruby_racer_runtime.

```
execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:47:in `rescue in block in call'
```

Source line:

```
raise wrap_error(e)
```

In the trace I'm not able to find back the filename where the error occurred, which is annoying when migrating 200 files.
It appears that some files had tree space instead of two when splitting a block of HAML options, like this:

```
%a{name: "copy",
   class: 'btn btn-default'}
```

This was previously not causing any trouble.
Would be nice to know quickly precisely where are the mistakes in the error.

**Comment by mathieujobin** [comment]
duplicate issue at best. no need to keep this open

please reopen if I am wrong

**Comment by mathieujobin** [comment]
please check #119 and #121, I think that's all the same issue. I would like to know if this was fixed in in more recent version.
