### ISSUE TITLE
Version 1.17 causes serious breakage

### ISSUE THREAD

**Issue by thomasbalsloev** [emilioforrer/haml_coffee_assets#161]
Hi and thank you for your great work on this gem.

After upgrading to version 1.17.0 the jst.hamlc templates (most anyway) stopped working in our app.

JS console error (if that helps):
jquery.self.js?body=1:1474 Uncaught Error: Syntax error, unrecognized expression: msp/templates/layout
    at Function.Sizzle.error (http://localhost:3000/assets/jquery.self.js?body=1:1474:8)
    at Sizzle.tokenize (http://localhost:3000/assets/jquery.self.js?body=1:2088:11)
    at Sizzle.select (http://localhost:3000/assets/jquery.self.js?body=1:2489:20)
    at Function.Sizzle [as find](http://localhost:3000/assets/jquery.self.js?body=1:880:9)
    at jQuery.fn.init.find (http://localhost:3000/assets/jquery.self.js?body=1:2705:11)
    at jQuery.fn.init (http://localhost:3000/assets/jquery.self.js?body=1:2822:38)
    at Object.jQuery [as $](http://localhost:3000/assets/jquery.self.js?body=1:74:10)
    at Marionette.TemplateCache.loadTemplate (http://localhost:3000/assets/plugins/common/backbone.marionette.self.js?body=1:1186:31)
    at Marionette.TemplateCache.load (http://localhost:3000/assets/plugins/common/backbone.marionette.self.js?body=1:1174:25)
    at Function.get (http://localhost:3000/assets/plugins/common/backbone.marionette.self.js?body=1:1136:27)

I traced the cause to this commit in transformer.rb:

https://github.com/emilioforrer/haml_coffee_assets/commit/9f02cabc7575cd60b2f0c0ae75a2cc082de4e2eb

Changing back to :filename makes the problem go away.

Debug output from "input" param in method "sef.call":
:filename => /home/tb/workspace/web/site_testing/app/assets/javascripts/msp/templates/layout.js.jst.hamlc
:name     => msp/templates/layout

Some env info:
$ruby --version
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]

Just ask me for more info and I'll provide it if I can.

Best regards,
Thomas Balsløv.

**Comment by TheKidCoder** [comment]
Can you post your HamlCoffeeAssets config? Specifically if you use `config.hamlcoffee.name_filter`

**Comment by P9GIT** [comment]
Hi. Thanks for getting back to me on this.

We have no name_filter option configured (in fact no HamlCoffeeAssets config at all).
When reading the "Template name" doc section I get the impression that the "name_filter" config does not apply when the templates are named jst.hamlc because the Sprockets JST processor does it's magic in that case.

**Comment by raman162** [comment]
The issue that I have is that my custom namespace is not being set. In my config/application.rb i have this code:
`config.hamlcoffee.namespace= 'window.ABC'`

I get an error in js that says `Uncaught ReferenceError: ABC is undefined`

This error only occurs after I upgraded from 1.16.0 to 1.17.0

**Comment by TheKidCoder** [comment]
@P9GIT Are you still having issues with filenames?

**Comment by P9GIT** [comment]
@TheKidCoder 

Hi. 
Yes, it is still an issue when we go to 1.17.0.
We're moving to Rails 4.2 and this forced us to use 1.17.0.
We have subsequently patched HamlCoffeeAssets via an initializer:

```
# coding: UTF-8

module HamlCoffeeAssets
  # Haml Coffee Sprockets processor
  #
  class Transformer

    def self.run(filename, name, source, context)
      jst  = !!(filename =~ /\.jst\.hamlc(?:\.|$)/)
      name = HamlCoffeeAssets.config.name_filter.call(name) if HamlCoffeeAssets.config.name_filter && !jst

      HamlCoffeeAssets::Compiler.compile(name, source, !jst)
    end

    def self.call(input)
      filename = input[:filename]
      name = input[:name]
      source   = input[:data]
      context  = input[:environment].context_class.new(input)

      result = run(filename, name, source, context)
      context.metadata.merge(data: result)
    end
  end
end
```

Best regards,
Thomas.

**Comment by mathieujobin** [comment]
Could anyone confirm this patch is still required? or has been applied already?

**Comment by mathieujobin** [comment]
I need to compare this more carefully, but I think the changes in this fork includes this patch

https://github.com/tiagotex/haml_coffee_assets

**Comment by mathieujobin** [comment]
please reopen if you still experience a problem with 1.20

**Comment by thomasbalsloev** [comment]
I can confirm that version 1.20.0 fixes the need for this patch.

Thanks @mathieujobin
