### ISSUE TITLE
Hyphens in template names are being replaced with underscores

### ISSUE THREAD

**Issue by ruipserra** [emilioforrer/haml_coffee_assets#163]
Currently using version 1.17.0.

I have some templates named like so:
`app/templates/_with-hyphens.hamlc`

These get stored in `JST` with the hyphens replaced by underscores, eg: `JST["app/templates/_with_hyphens"]`.

Seems like [this line](https://github.com/emilioforrer/haml_coffee_assets/blob/master/lib/js/hamlcoffee.js#L507) is the culprit. Note this is after the `name_filter` is applied. My `name_filter` is a simple pass-through (`->(name) { name }`).

You should be able to reproduce this in IRB:

```ruby
HamlCoffeeAssets.config.name_filter = ->(name) { name }
HamlCoffeeAssets::Transformer.run('a-name-with-hyphens', '', nil)
# =>
# (function() {
#   if (window.JST == null) {
#     window.JST = {};
#   }
# 
#   window.JST['a_name_with_hyphens'] = function(context) {
#     return (function() {
#       var $o;
#       $o = [];
#       return $o.join("\n");
#     }).call(window.HAML.context(context));
#   };
# 
# }).call(this);
```

The template name should not be modified after `name_filter` is called.

**Comment by TheKidCoder** [comment]
I would imagine that line exists in hamlcoffee to allow for dot-syntax access. Although, that of course is broken by allowing slashes so I'm not really sure why thats the case. I would be worried about breaking changes here, so I think if we add this it will need to be under a config flag.

**Comment by mathieujobin** [comment]
Was this with sprockets 2.x or 3.x ? Can you please specify sprockets version?

Could this be related with #152 ?

Please try the latest master, I just merged a patch which we need for sprockets 3.x

Maybe it solves your problem. I will close as there are no further actions for us here. But feel free to reopen with more details if you can still reproduce using master branch of this gem and sprockets 3.x

Sprockets 2.x will no longer be supported, unless someone steps up for it.

Thanks
