### ISSUE TITLE
find_asset doesn't work when config.assets.compile = false

### ISSUE THREAD

**Issue by mhuggins** [emilioforrer/haml_coffee_assets#165]
We're upgrading from Rails 4.1 to 4.2, and haml_coffee_assets breaks due to `config.assets.compile = false` being set in our application's environment.  When that is false, `Rails.application.assets` returns `nil`, which means that `find_asset` doesn't work.

The alternative appears to be to use `Rails.application.assets_manifest`, but it's not completely synonymous since you need to resolve assets, which was provided for free in the `find_assets` method.

**Comment by TheKidCoder** [comment]
Do any other assets appear in your `Rails.application.assets` hash? As I understand it, this is rails issue and not specific to haml_coffee

**Comment by mathieujobin** [comment]
I am taking a guess this is outdated.
please re-open if this is still an issue
