### ISSUE TITLE
DEPRECATION WARNING: Single arity template handlers are deprecated

### ISSUE THREAD

**Issue by masterkain** [emilioforrer/haml_coffee_assets#174]
```
guard_1             | DEPRECATION WARNING: Single arity template handlers are deprecated. Template handlers must
guard_1             | now accept two parameters, the view object and the source for the view object.
guard_1             | Change:
guard_1             |   >> HamlCoffeeAssets::ActionView::TemplateHandler.call(template)
guard_1             | To:
guard_1             |   >> HamlCoffeeAssets::ActionView::TemplateHandler.call(template, source)
guard_1             |  (called from <top (required)> at /usr/src/app/config/environment.rb:5)
```

**Comment by tiagotex** [comment]
This gem seems to be unmaintained for a few years. 

I've added the fixes suggested in the open PRs in a [fork of this repo] https://github.com/tiagotex/haml_coffee_assets), you can use it to avoid the known bug and this deprecation warning, but it's better to start planning a migration.

To use my fork do:

```
gem "haml_coffee_assets", git: 'https://github.com/tiagotex/haml_coffee_assets'
```

**Comment by mathieujobin** [comment]
I will introduce this change in an upcoming release.
I need CI to be more stable. I have one problem left with jasmine with ruby 2.5+ see #178 
once that's fix, things can move forward, but I don't know anything about jasmine ...

**Comment by tiagotex** [comment]
Thank you for releasing the new version. I guess we can close this issue :)

**Comment by mathieujobin** [comment]
Thanks for the ping ! I believe latest release indeed fixed this.
please open new issue or (even better a pull request) if you encounter any problems
