### ISSUE TITLE
Anybody still maintaining this gem?

### ISSUE THREAD

**Issue by mathieujobin** [emilioforrer/haml_coffee_assets#175]
Does the current maintainer need any help?
Do we need a new maintainer?
Anyone interested?

**Comment by mathieujobin** [comment]
@emilioforrer ?

**Comment by TheKidCoder** [comment]
@mathieujobin Unfortunately I haven't used this gem for a number of years now. I'm happy to hand off the baton to new maintainers.

**Comment by mathieujobin** [comment]
@TheKidCoder I don't mind doing the code review and merges/releases.

I have a project that still uses it, so it can be useful to have write access when I upgrade that app.

But I won't be able to actively fix bugs and do support.

**Comment by mathieujobin** [comment]
Thank you @TheKidCoder for giving me access.

I think a good first step is to have working CI

https://github.com/emilioforrer/haml_coffee_assets/pull/172/files

Anyone who wants to contribute, please do. I will be watching for PRs

**Comment by emilioforrer** [comment]
Hi! @mathieujobin , I just made you contributor and sent you an invite to ruby gems for this gem.

Since I don't know how to contact you, I send an invitation in your LinkedIn account in case you are interested in taking the ownership of the repository, let me know there.
