### ISSUE TITLE
Rails 6.0 - undefined method 'append=' for nil:NilClass

### ISSUE THREAD

**Issue by pwenig** [emilioforrer/haml_coffee_assets#176]
I work on an application that has been around for quite some time. We're trying to update from Rails 5.2 to 6.0 and seem to be running into an issue where `undefined method 'append=' for nil:NilClass` is thrown after the initial load. I know that this is being caused by `haml_coffee_assets`

rails (6.0.3.4)
ruby (2.7.2)
haml_coffee_assets (1.18.0)
sprockets (4.0.2)

Has anyone run into this?

**Comment by mathieujobin** [comment]
Support for 6.0 added in v1.20.0

please update and try again
