### ISSUE TITLE
Can you add Rails 7 support?

### ISSUE THREAD

**Issue by rmeritz** [emilioforrer/haml_coffee_assets#183]
Currently when I try and upgrade this gem is locked:

```
    haml_coffee_assets was resolved to 1.20.0, which depends on
      railties (>= 4.2, < 6.2) was resolved to 6.1.4.4, which depends on
        actionpack (= 6.1.4.4)
```

**Comment by mathieujobin** [comment]
You can use this branch in the meantime

`gem 'haml_coffee_assets', github: 'emilioforrer/haml_coffee_assets', branch: 'rails7'`

it's not ready for merging yet, but so far so good for me. If you encounter any issue, I would appreciate a pull request very much.

**Comment by mathieujobin** [comment]
There are a few tests failures, if you figure them out before me, that would be super helpful.
I don't think I'll be able to dig this in the short term…
https://github.com/emilioforrer/haml_coffee_assets/pull/184
