### ISSUE TITLE
.hamlc is unexpectedly processed by JstProcessor

### ISSUE THREAD

**Issue by voducvu** [emilioforrer/haml_coffee_assets#189]
**Problem**
The template function is unexpectedly generated into namespace window.JST['templates/<template_name>]. When we access this template, it returns undefined.

    (function() { this.JST || (this.JST = {}); this.JST["templates/activities/default_content"] = (function() { //unexpected wrapper
      if (window.JST == null) {
        window.JST = {};
      }
    
      window.JST['activities/default_content'] = function(context) {
        return (function() {
          var $o;
          $o = [];
          $o.push("<div class='video-outer'>\n  <div class='videoSmall'>\n    <div class='js-video-player'></div>\n  </div>\n</div>");
          return $o.join("\n").replace(/\s(?:id|class)=(['"])(\1)/mg, "");
        }).call(window.HAML.context(context));
      };
    }).call(this);;}).call(this);
**Findings**
The .hamlc is processed by JstProcessor unexpectedly. It should be handled by HamlCoffeeAssets::Transformer only.

        config.assets.configure do |env|
          if env.respond_to?(:register_transformer)
            env.register_mime_type 'text/hamlc', extensions: ['.hamlc', '.jst.hamlc']
            env.register_transformer 'text/hamlc', 'application/javascript', ::HamlCoffeeAssets::Transformer
            env.register_transformer 'text/hamlc', 'application/javascript+function', ::HamlCoffeeAssets::Transformer
          end
**Suggestion**
We should separate the mimetype for .hamlc and .jst.haml

        config.assets.configure do |env|
          if env.respond_to?(:register_transformer)
            env.register_mime_type 'text/hamlc', extensions: ['.hamlc']
            env.register_mime_type 'text/jst+hamlc', extensions: ['.jst.hamlc']
            env.register_transformer 'text/hamlc', 'application/javascript', ::HamlCoffeeAssets::Transformer
            env.register_transformer 'text/jst+hamlc', 'application/javascript+function', ::HamlCoffeeAssets::Transformer
          end

**Comment by mathieujobin** [comment]
I'm sorry, I'm not sure anyone will have time to be looking at this problem in depth.
if you do find a solution, please open a pull request.

thanks

**Comment by voducvu** [comment]
hi @mathieujobin, I opened a PR here https://github.com/emilioforrer/haml_coffee_assets/pull/190. Please help proceed to merge it when you have time.
Thanks

**Comment by mathieujobin** [comment]
Thanks for the fix @voducvu 

I merged #191 which appears equivalent, but please do let me know if you find that something is missing.

will release shortly in v1.25.0
