### ISSUE TITLE
rails 8.0 support

### ISSUE THREAD

**Issue by balakirevs** [emilioforrer/haml_coffee_assets#195]
Could not find compatible versions

Because haml_coffee_assets >= 1.26.0 depends on railties >= 5.2, < 7.3
  and rails >= 8.0.0 depends on railties = 8.0.0,
  haml_coffee_assets >= 1.26.0 is incompatible with rails >= 8.0.0.
So, because Gemfile depends on rails ~> 8.0.0
  and Gemfile depends on haml_coffee_assets ~> 1.26.0,
  version solving has failed.

**Comment by mathieujobin** [comment]
if you open a PR, I can merge it ... and release.

**Comment by balakirevs** [comment]
https://github.com/emilioforrer/haml_coffee_assets/pull/196

**Comment by mathieujobin** [comment]
Tagged and published.
Successfully registered gem: [haml_coffee_assets (1.27.0)
](https://rubygems.org/gems/haml_coffee_assets/versions/1.27.0)
